### ISSUE TITLE
don't write python for optional arguments...

### ISSUE THREAD

**Issue by Roger-luo** [QuantumBFS/YaoBlocksQobj.jl#10]
https://github.com/QuantumBFS/YaoBlocksQobj.jl/blob/148497686b602c0cdd46681d6c9cabb6528c4be7/src/qobj.jl#L44

this is not how you write optional arguments in Julia, let's use a kwargs instead, and annotate the kwargs as `Bool`

**Comment by Sov-trotter** [comment]
Okay Sure. BTW you mean only for this specific method or the others too?
Also I am not able to understand the need for annotating the kwargs as `Bool` ?

**Comment by Roger-luo** [comment]
sorry, I meant for this line

https://github.com/QuantumBFS/YaoBlocksQobj.jl/blob/148497686b602c0cdd46681d6c9cabb6528c4be7/src/qobj.jl#L48

I think the interface of this function could use some redesign, consider using Configurations.jl to define the valid options first, then use the option type as an argument. 

for interface function, we would prefer to put annotations on argument to error intermediately when there is a invliad input.

**Comment by Roger-luo** [comment]
to be more specific, I'm thinking 

```julia
function create_experiment(qc::Vector{<:AbstractBlock{N}}, options::ExpOptions)
end
```

and we can pass the kwargs like this in top-level

https://github.com/QuantumBFS/YaoBlocksQobj.jl/blob/148497686b602c0cdd46681d6c9cabb6528c4be7/src/qobj.jl#L23

```julia
convert_to_qobj(qc::Vector{<:AbstractBlock}; kw...) = convert_to_qobj(qc, ExpOptions(;kw...))
```

this should give us the validator for experiment options.

**Comment by Roger-luo** [comment]
the general idea is that in Python due to the lack of multiple dispatch, one has to do 

```python
def func(x = None):
    if x isa None:
         pass
    else:
         pass
```

to handle optional arguments, but we don't have to do it here and instead just dispatch on `Nothing` and `Vector` or other things

**Comment by Sov-trotter** [comment]
Yeah. This sounds valid. 
My main objective [here](https://github.com/QuantumBFS/YaoBlocksQobj.jl/blob/148497686b602c0cdd46681d6c9cabb6528c4be7/src/qobj.jl#L48-L49) was to simply ensure if the `header` and `config` were sent by the user. Since that decides what is dispatched further. 

The main confusion that still remains here is if there exists any better way to take input for optional stuff(header config for respective experiments). Since we take a list of `AbstractBlock` as input, how should the optional stuff be received?
Which for now is done by taking a list of  headers and configs separately.

 
Also there can be permutations where one inputs headers but not configs.

> just dispatch on Nothing and Vector or other things

This sounds reasonable.

**Comment by Roger-luo** [comment]
> The main confusion that still remains here is if there exists any better way to take input for optional stuff(header config for respective experiments). Since we take a list of AbstractBlock as input, how should the optional stuff be received?

we can have a Qobj specific block here (say `Experiment{N} <: AbstractBlock{N}`), that takes a `ChainBlock` and a `config` and `header`, then accept a list of them and lower them to Qobj.

**Comment by Roger-luo** [comment]
also I think the first arugment should always be `Vector` I don't think we want to accept any high dimensional thing.
